// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_validate
Rcpp::List cpp_validate(Rcpp::List params);
RcppExport SEXP _skindiff_cpp_validate(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_validate(params));
    return rcpp_result_gen;
END_RCPP
}
// cpp_simulate
Rcpp::List cpp_simulate(Rcpp::List params, bool show_progress);
RcppExport SEXP _skindiff_cpp_simulate(SEXP paramsSEXP, SEXP show_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< bool >::type show_progress(show_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_simulate(params, show_progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_skindiff_cpp_validate", (DL_FUNC) &_skindiff_cpp_validate, 1},
    {"_skindiff_cpp_simulate", (DL_FUNC) &_skindiff_cpp_simulate, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_skindiff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
