# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
.dskin.binding.geometry <- function(json_parameter) {
    .Call(`_dskin_getGeometry`, json_parameter)
}

#' @keywords internal
.dskin.binding.simulate <- function(json_parameter, write_to_R, write_to_files) {
    .Call(`_dskin_simulate`, json_parameter, write_to_R, write_to_files)
}

