# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cpp_validate <- function(params) {
    .Call(`_skindiff_cpp_validate`, params)
}

.cpp_simulate <- function(params, show_progress = FALSE) {
    .Call(`_skindiff_cpp_simulate`, params, show_progress)
}

